/** Pro feature: a standalone, self-contained HTML report you can hand to a client. */

const STATUS_COLOR = { fail: '#d1242f', warn: '#bf8700', pass: '#1a7f37', skip: '#8c959f', error: '#8c959f' };

export function buildHtmlReport(report) {
  const counts = { pass: 0, warn: 0, fail: 0, skip: 0, error: 0 };
  for (const r of report.results) counts[r.status] = (counts[r.status] || 0) + 1;

  const rows = report.results.map((r) => `
    <section class="check">
      <h3><span class="pill" style="color:${STATUS_COLOR[r.status]};border-color:${STATUS_COLOR[r.status]}">${r.status.toUpperCase()}</span>
        ${esc(r.id)} · ${esc(r.title)}
        ${r.status === 'pass' || r.status === 'skip' ? '' : `<span class="sev">${esc(r.severity)} severity</span>`}</h3>
      <p class="sum">${esc(r.summary)}</p>
      ${r.details.map((d) => `<p class="detail">${esc(d)}</p>`).join('')}
      ${r.fix && (r.status === 'fail' || r.status === 'warn') ? `<pre class="fix">${esc(r.fix)}</pre>` : ''}
      ${r.ref ? `<p class="ref"><a href="${esc(r.ref)}">Reference</a></p>` : ''}
    </section>`).join('');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>QuickAudit — ${esc(hostOf(report.url))}</title>
<style>
  :root{--fg:#16181d;--muted:#6b7280;--line:#e5e7eb;--surface:#f7f8fa;color-scheme:light}
  *{box-sizing:border-box}
  /* This is a document to hand to someone, and it prints. It commits to a light page rather
     than following the reader's theme — without an explicit background it renders dark text
     on a dark canvas for anyone whose browser is in dark mode. */
  html{background:#fff}
  body{font:14px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;color:var(--fg);
       background:#fff;max-width:820px;margin:0 auto;padding:40px 24px}
  h1{font-size:22px;margin:0 0 4px}
  .target{color:var(--muted);word-break:break-all;margin:0 0 20px}
  .summary{display:flex;gap:20px;align-items:center;padding:16px;background:var(--surface);
           border:1px solid var(--line);border-radius:10px;margin-bottom:28px}
  .score{font-size:34px;font-weight:700;line-height:1}
  .score small{display:block;font-size:11px;font-weight:400;color:var(--muted)}
  .tally{display:flex;gap:18px;font-size:13px}
  .tally b{font-size:18px;display:block}
  .check{border-top:1px solid var(--line);padding:16px 0}
  .check h3{font-size:14px;margin:0 0 6px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}
  .pill{font-size:10px;font-weight:700;letter-spacing:.04em;padding:2px 6px;border:1px solid;border-radius:4px}
  .sev{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}
  .sum{margin:0 0 8px}
  .detail{color:var(--muted);font-size:13px;margin:0 0 5px;white-space:pre-wrap;word-break:break-word}
  .fix{background:var(--surface);border-left:3px solid #0b57d0;padding:10px 12px;
       font:12px/1.5 ui-monospace,Consolas,monospace;white-space:pre-wrap;overflow-x:auto;border-radius:0 6px 6px 0}
  .ref a{font-size:12px;color:#0b57d0}
  footer{margin-top:36px;padding-top:16px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}
  @media print{body{padding:0}.check{break-inside:avoid}}
</style></head><body>
<h1>QuickAudit report</h1>
<p class="target">${esc(report.url)}<br>${esc(new Date(report.scannedAt).toLocaleString())}</p>
<div class="summary">
  <div class="score">${report.score}<small>/ 100</small></div>
  <div class="tally">
    <div><b style="color:${STATUS_COLOR.fail}">${counts.fail}</b>failed</div>
    <div><b style="color:${STATUS_COLOR.warn}">${counts.warn}</b>warnings</div>
    <div><b style="color:${STATUS_COLOR.pass}">${counts.pass}</b>passed</div>
    <div><b style="color:${STATUS_COLOR.skip}">${counts.skip + counts.error}</b>skipped</div>
  </div>
</div>
${rows}
${report.notes?.length ? `<footer><b>Collection notes</b><br>${report.notes.map(esc).join('<br>')}</footer>` : ''}
<footer>Generated by QuickAudit. This is an automated configuration checklist, not a penetration test —
a clean report means the common misconfigurations are absent, not that the application is secure.</footer>
</body></html>`;
}

function hostOf(u) { try { return new URL(u).hostname; } catch { return u; } }
function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
